# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import completion_pb2 as completion__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = getattr(grpc, '__version__', 'unknown')
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    if GRPC_VERSION != 'unknown':
        _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

# Skip version check for now - the functionality should work with older versions
# if _version_not_supported and GRPC_VERSION != 'unknown':
#     raise RuntimeError(
#         f'The grpc package installed is at version {GRPC_VERSION},'
#         + f' but the generated code in completion_pb2_grpc.py depends on'
#         + f' grpcio>={GRPC_GENERATED_VERSION}.'
#         + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
#         + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
#     )


class CompletionServiceStub(object):
    """============ Service ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Completion = channel.unary_stream(
                '/completion.CompletionService/Completion',
                request_serializer=completion__pb2.CompletionRequest.SerializeToString,
                response_deserializer=completion__pb2.StreamingChunk.FromString,
                _registered_method=True)


class CompletionServiceServicer(object):
    """============ Service ============
    """

    def Completion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompletionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Completion': grpc.unary_stream_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=completion__pb2.CompletionRequest.FromString,
                    response_serializer=completion__pb2.StreamingChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'completion.CompletionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('completion.CompletionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompletionService(object):
    """============ Service ============
    """

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/completion.CompletionService/Completion',
            completion__pb2.CompletionRequest.SerializeToString,
            completion__pb2.StreamingChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
