from enum import Enum

class SecretEnum(Enum):
    OPENAI_SECRET_KEY = "OPENAI_SECRET_KEY"
    POSTGRES_CONN_STRING = "POSTGRES_CONN_STRING"
    FERNET_SECRET = "FERNET_SECRET"

    LANGFUSE_SECRET_KEY = "LANGFUSE_SECRET_KEY"
    LANGFUSE_PUBLIC_KEY = "LANGFUSE_PUBLIC_KEY"    
    LANGFUSE_HOST = "LANGFUSE_HOST"
    
    MODULE_HOST = "MODULE_HOST"
    MODULE_API_KEY = "MODULE_API_KEY"
    
    OPENAI_API_KEY = "OPENAI_API_KEY"