from enum import Enum

class SecretEnum(Enum):
    OPENAI_SECRET_KEY = "OPENAI_SECRET_KEY"
    POSTGRES_CONN_STRING = "POSTGRES_CONN_STRING"
    FERNET_SECRET = "FERNET_SECRET"

    LANGFUSE_SECRET_KEY = "LANGFUSE_SECRET_KEY"
    LANGFUSE_PUBLIC_KEY = "LANGFUSE_PUBLIC_KEY"    
    LANGFUSE_HOST = "LANGFUSE_HOST"
    
    MODULE_HOST = "MODULE_HOST"
    MODULE_API_KEY = "MODULE_API_KEY"
    
    OPENAI_API_KEY = "OPENAI_API_KEY"
    
    # Logging
    LOG_LEVEL = "LOG_LEVEL"
    
    # MinIO Configuration
    MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY"
    MINIO_SECRET_KEY = "MINIO_SECRET_KEY"
    MINIO_ENDPOINT = "MINIO_ENDPOINT"
    MINIO_PORT = "MINIO_PORT"
    MINIO_GAMES_BUCKET = "MINIO_GAMES_BUCKET"
    MINIO_BROWSER_URL = "MINIO_BROWSER_URL"
    
    # Langfuse Configuration
    LANGFUSE_PROMPT_LABEL = "LANGFUSE_PROMPT_LABEL"
    LANGFUSE_VERSION_ID = "LANGFUSE_VERSION_ID"
    
    # Kafka Configuration
    KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"
    KAFKA_TOPIC_REQUEST = "KAFKA_TOPIC_REQUEST"
    KAFKA_TOPIC_RESPONSE = "KAFKA_TOPIC_RESPONSE"
    KAFKA_GROUP_ID = "KAFKA_GROUP_ID"