from enum import Enum

class SecretEnum(Enum):
    # Database Connection String
    POSTGRES_CONN_STRING = "POSTGRES_CONN_STRING"
    
    # Secret for Fernet encryption
    FERNET_SECRET = "FERNET_SECRET"
    
    # Langfuse Configuration
    LANGFUSE_SECRET_KEY = "LANGFUSE_SECRET_KEY"
    LANGFUSE_PUBLIC_KEY = "LANGFUSE_PUBLIC_KEY"
    LANGFUSE_HOST = "LANGFUSE_HOST"
    LANGFUSE_PROMPT_LABEL = "LANGFUSE_PROMPT_LABEL"
    LANGFUSE_VERSION_ID = "LANGFUSE_VERSION_ID"
    
    # Module Service
    MODULE_HOST = "MODULE_HOST"
    MODULE_API_KEY = "MODULE_API_KEY"
    
    # MinIO Configuration
    MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY"
    MINIO_SECRET_KEY = "MINIO_SECRET_KEY"
    MINIO_ENDPOINT = "MINIO_ENDPOINT"
    MINIO_PORT = "MINIO_PORT"
    MINIO_GAMES_BUCKET = "MINIO_GAMES_BUCKET"
    MINIO_LIBRARY_BUCKET = "MINIO_LIBRARY_BUCKET"
    MINIO_BROWSER_URL = "MINIO_BROWSER_URL"
    
    # Model API Keys
    OPENAI_API_KEY = "OPENAI_API_KEY"
    ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
    DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"
    GOOGLE_API_KEY = "GOOGLE_API_KEY"
    GOOGLE_GENAI_USE_VERTEXAI = "GOOGLE_GENAI_USE_VERTEXAI"
    
    # Qdrant Configuration
    QDRANT_URL = "QDRANT_URL"
    QDRANT_API_KEY = "QDRANT_API_KEY"
    QDRANT_LIBRARY_COLLECTION_NAME = "QDRANT_LIBRARY_COLLECTION_NAME"
    QDRANT_MESSAGES_COLLECTION_NAME = "QDRANT_MESSAGES_COLLECTION_NAME"
    
    # FE Webhook
    WEBHOOK_URL = "WEBHOOK_URL"
    
    # Preview API URL
    APP_PREVIEW_URL = "APP_PREVIEW_URL"
    
    # Privy Wallet Configuration
    PRIVY_WALLET_ADDRESS = "PRIVY_WALLET_ADDRESS"
    USER_PRIVY_TEST_WALLET = "USER_PRIVY_TEST_WALLET"
    
    # Kafka Configuration
    KAFKA_BROKERS = "KAFKA_BROKERS"
    KAFKA_GROUP_ID = "KAFKA_GROUP_ID"
    KAFKA_AGENT_MENTION_TOPIC = "KAFKA_AGENT_MENTION_TOPIC"
    KAFKA_AGENT_REPLY_TOPIC = "KAFKA_AGENT_REPLY_TOPIC"

    # Extra Settings
    MAX_WORKERS = "MAX_WORKERS"
    GRPC_PORT = "GRPC_PORT"
    LOG_LEVEL = "LOG_LEVEL"
    
    # 0x API Key
    ZERO_X_API_KEY = "ZERO_X_API_KEY"